version: "3"

services: 
  api-server:
    image: api-toolbox
    build:
      dockerfile: Dockerfile 
      context: ./api
    ports: 
      - "5000:5000" 
    networks:
      - mern-app

  front-react: 
    image: front-toolbox
    build: 
      dockerfile: Dockerfile
      context: ./front
    stdin_open: true
    ports: 
      - "3000:3000"
    networks:
      - mern-app


networks:
  mern-app:
    driver: bridge
    